name: Basic Jobs Done

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  echo-vars-and-secrets:
    name: 1 - Echo Variables and Secrets
    runs-on: ubuntu-latest
    environment: development
    env:
      MY_VARIABLE: ${{ vars.MY_VARIABLE }}
      MY_SECRET: ${{ vars.MY_SECRET }}
    steps:
      - name: Echo repository variable
        run: echo "Repository variable = $MY_VARIABLE"

      - name: Echo repository secret (value is masked)
        run: echo "Repository secret = $MY_SECRET"
